public enum EDialogueID { FRHEY, FRHINEEDHELP, FRDONTUWORKATLETTINGS, FRHELP, FRNEEDURHELP, FRCANUREFERME, 
    FRYRUHOSTILE, FRBORING2DAY, FRBITMUCH, FRCANUNDERSTAND, FRIMJARED,
    FRWHAT2SAYNEXT, FRCANTWAITTONAP, FRNOWTHATWEKNOW, FRWHEREDOUWORK, FRATLETTINGSRIGHT, FRAPPLIEDMYSELF,
    FRTHEYBEHINDMYDAD, FRITSBEENAWEEK, FRWUDITALK2U, FRAPPHIGHLIGHT, FRUKNOWALOT, FRWUDBHELP, FRTOOKULONGENUF,
    FRMAYBEICANHELP
}