public enum EDialogueID { FRHEY, FRHINEEDHELP, FRDONTUWORKATLETTINGS, FRHELP, FRNEEDURHELP, FRCANUREFERME, 
    FRYRUHOSTILE, FRBORING2DAY, FRBITMUCH, FRCANUNDERSTAND, FRIMJARED,
    FRWHAT2SAYNEXT, FRCANTWAITTONAP, FRNOWTHATWEKNOW, FRWHEREDOUWORK, FRATLETTINGSRIGHT, FRAPPLIEDMYSELF,
    FRIDONTWORK, FRTHEYBEHINDMYDAD, FRITSBEENAWEEK, FRWUDITALK2U, FRAPPHIGHLIGHT, FRUKNOWALOT, FRWUDBHELP, 
    FRTOOKULONGENUF, FRMAYBEICANHELP, FRONETRACKMIND, FRWILLTALK2BULLY, FRWONTTALK2BULLY, FRCANTBELIEVEUFELL, 
    FRSTILLTALK2ROGER, FRIHANDLEDIT, FRSTUPIDBULLY, FRTRYNAFIGUREOUT, FRLYINGABTBULLY, FRYESREALLYHANDLEDBULLY,

    BULLYHEY, BULLYWHATSWITHSIS, BULLYPLSTELLIFKNOW, BULLYWHYBULLYING, BULLYSISUPSETWIDU, BULLYSTOPBOTHERINGHER,
    BULLYGOODIFUSTOP, BULLYUASKEDFORIT, BULLYSORRYIMLEAVING, BULLYBRINGITON, BULLYPASSINGBY, BULLYHADENUF,

    JANITORIHEARD, JANITORDOUKNWMYDAD, JANITORRUCLOSEWIDMGR, JANITORSTILLWANTME2CRACK, JANITORSORTWOUTCRACKING,
    JANITORIGOTCODE, JANITORSTILLWORKING, JANITORREPEATSECRET, JANITORTHANKS,
    JANITORDONTPRETEND, JANITORIWANTEDTOKNW, JANITORJUSTCURIOUS, JANITORMGRBMAILINGU, JANITORIWANNATAKEHIMDOWN, 
    JANITORHOPELESSGUY, JANITORMGRINVOLVEDININCIDENT, JANITORGOTMYREASONS, JANITORTURNINURFAVOR, JANITORCANTTELLU, 
    JANITORTELLMEABTDIRT, JANITORIFMGRJAILED, JANITORITHINKSO, JANITORDANGEROUSMISSION, JANITORTHECODEISCORRECT,
    JANITORTHECODEISWRONG, JANITORJOGMEMORY, JANITORWHATWEREURDEEDS,

    MGRNEED2TALK, MGRABTAYRAGO, MGRUKNOWWHATIMSAYIN, MGRABTSTORAGEUNIT, MGRONGROVEST, MGRONTROVEST, MGRDONTPRETEND,
    MGRDONTLIE, MGRKATARINA, MGRKATHERINE
}