public enum PlayerStates
{
    NEUTRAL, ACQUAINTANCE, FRNDBULLYMENTIONED, WILLTALK2BULLY, BULLYDEFEATED, BULLYFOUGHT,
    SAFECRACKOFFERED, SAFECRACKACCEPTED, SAFECRACKED, MGRSECRETFOUND, MGRARRESTED
};
